from brute.brute_force import brute_force_non_constrained, brute_force_constrained
from greedy.greedy_algorithm import greedy_algorithm_constrained,greedy_algorithm_non_constrained
from test_algorithm import TestAlgorithm

test_algorithm_instance = TestAlgorithm()

# Test unconstrained algorithm
test_algorithm_instance.run_algorithm_tests(brute_force_non_constrained, "Brute Force non Constrained algorithm")
test_algorithm_instance.run_algorithm_tests(greedy_algorithm_non_constrained, "Greedy_algorithm_non_constrained")


